# Source: external-secrets/templates/webhook-secret.yaml
apiVersion: v1
kind: Secret
metadata: # kpt-merge: external-secrets/external-secrets-webhook
  name: external-secrets-webhook
  namespace: external-secrets
  labels:
    helm.sh/chart: external-secrets-0.5.8
    app.kubernetes.io/name: external-secrets-webhook
    app.kubernetes.io/instance: external-secrets
    app.kubernetes.io/version: v0.5.8
    external-secrets.io/component: webhook
  annotations:
    internal.kpt.dev/upstream-identifier: '|Secret|external-secrets|external-secrets-webhook'
