# Source: external-secrets/templates/validatingwebhook.yaml
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata: # kpt-merge: /secretstore-validate
  name: secretstore-validate
  labels:
    external-secrets.io/component: webhook
  annotations:
    internal.kpt.dev/upstream-identifier: 'admissionregistration.k8s.io|ValidatingWebhookConfiguration|default|secretstore-validate'
webhooks:
- name: validate.secretstore.external-secrets.io
  rules:
  - apiGroups:
    - external-secrets.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - secretstores
    scope: Namespaced
  clientConfig:
    service:
      namespace: external-secrets
      name: external-secrets-webhook
      path: /validate-external-secrets-io-v1beta1-secretstore
  admissionReviewVersions:
  - v1
  - v1beta1
  sideEffects: None
  timeoutSeconds: 5
- name: validate.clustersecretstore.external-secrets.io
  rules:
  - apiGroups:
    - external-secrets.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - clustersecretstores
    scope: Cluster
  clientConfig:
    service:
      namespace: external-secrets
      name: external-secrets-webhook
      path: /validate-external-secrets-io-v1beta1-clustersecretstore
  admissionReviewVersions:
  - v1
  - v1beta1
  sideEffects: None
  timeoutSeconds: 5
