# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  LIQUIBASE_VERSION: '4.5.0'

stages:
  - stage: Build
    jobs:
      - job: Build
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.x'
              addToPath: true

          - script: |
              echo "Installing Liquibase..."
              wget https://github.com/liquibase/liquibase/releases/download/v$(LIQUIBASE_VERSION)/liquibase-$(LIQUIBASE_VERSION).tar.gz
              tar -zxvf liquibase-$(LIQUIBASE_VERSION).tar.gz
              export PATH=$PATH:$(pwd)/liquibase
            displayName: 'Install Liquibase'

          - script: |
              echo "Validating Liquibase changesets..."
              liquibase 
            displayName: 'Validate Liquibase'

          - publish: $(Pipeline.Workspace)
            artifact: LiquibaseScripts
            displayName: 'Publish Liquibase Scripts'
