apiVersion: fn.kpt.dev/v1alpha1
kind: StarlarkRun
metadata: # kpt-merge: /remove-labels
  name: remove-labels
  annotations:
    config.kubernetes.io/local-config: "true"
    internal.kpt.dev/upstream-identifier: 'fn.kpt.dev|StarlarkRun|default|remove-labels'
source: |-
  def remove_labels(resources):
    for resource in resources:
      if "labels" in resource.get("metadata"):
        resource["metadata"]["labels"].pop("app.kubernetes.io/managed-by", "")

  remove_labels(ctx.resource_list["items"])
