# Source: external-secrets/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata: # kpt-merge: external-secrets/external-secrets
  name: external-secrets
  namespace: external-secrets22
  labels:
    helm.sh/chart: external-secrets-0.5.8
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/instance: external-secrets
    app.kubernetes.io/version: v0.5.8
  annotations:
    internal.kpt.dev/upstream-identifier: '|ServiceAccount|external-secrets|external-secrets'
